# Generated by Django 5.0.4 on 2024-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('cover_letter', models.FileField(upload_to='cover_letters/')),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
