# Generated by Django 5.0.4 on 2024-06-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_jobpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='apply_link',
        ),
    ]
